version: '3'

services:
  web:
    depends_on:
      - "db"
    environment:
      - "TZ=Europe/Paris"
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: predictable.farm.dashboard.web
    ports:
    - 80:80
    volumes:
    - .:/usr/src/app/
    - /usr/src/app/server/node_modules
  db:
    environment:
    - "TZ=Europe/Paris"
    image: cassandra
    container_name: predictable.farm.dashboard.db

    volumes:
    #- ./predictable.farm.dashboard/:/usr/src/app/
    - test-cassandra:/var/lib/cassandra/
    #- ./mysql/:/var/lib/mysql2/
    restart: always

volumes:
  test-cassandra:
