
version: '3'

services:
  web:
    environment:
      - "TZ=Europe/Berlin"
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: predictable-dashboard
    ports:
    - 80:80
    volumes:
    - .:/usr/src/app/
    - /usr/src/app/server/node_modules
