
version: '3'

services:
  web:
    depends_on:
      - "db"
    environment:
      - "TZ=Europe/Berlin"
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: predictable-dashboard
    ports:
    - 80:80
    volumes:
    - .:/usr/src/app/
    - /usr/src/app/server/node_modules
  db:
    environment:
    - "TZ=Europe/Berlin"
    image: cassandra-brice3
    container_name: local-test-ecf-berlin_predictable-cassandra2

    volumes:
    #- ./dashboard-predictable-farm/:/usr/src/app/
    - test-cassandra:/var/lib/cassandra/
    #- ./mysql/:/var/lib/mysql2/
    restart: always


volumes:
  test-cassandra:
