
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
          - TZ=Europe/Berlin
    container_name: predictable-dashboard
    ports:
    - 80:80
    volumes:
    - .:/usr/src/app/
    - /usr/src/app/server/node_modules
